Fix broken linters in proton test_instrumentation to recover pre-commit (#675)
Summary:
Fix linter errors introduced yesterday (noticed by oss errors from a newer unrelated diff) and notice some unit test failures as below

```
FAILED third_party/proton/test/test_instrumentation.py::test_record[context_manager] - ZeroDivisionError: division by zero
FAILED third_party/proton/test/test_instrumentation.py::test_tree[triton] - IndexError: list index out of range
FAILED third_party/proton/test/test_instrumentation.py::test_tree[None] - IndexError: list index out of range
FAILED third_party/proton/test/test_instrumentation.py::test_trace - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
FAILED third_party/proton/test/test_instrumentation.py::test_multi_session - IndexError: list index out of range
FAILED third_party/proton/test/test_instrumentation.py::test_gmem_buffer - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Pull Request resolved: https://github.com/facebookexperimental/triton/pull/675

Reviewed By: fywkevin

Differential Revision: D87363838

Pulled By: dshi7

fbshipit-source-id: 966d13070a2d2f456525a048bd32f8dd53d81ac7