[TLX] More mm shapes for blackwell_gemm_ws in correctness tests (#1035)
Summary:
Need to rule out some shapes: (1) stride-alignment errors (K%8 != 0) (2) very large K (K>>M, K>>N)

Pull Request resolved: https://github.com/facebookexperimental/triton/pull/1035

Test Plan:
pytest third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes -v

```
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[192x448x147456] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[192x448x294912] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[192x448x442368] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[192x448x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x128x294912] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x128x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x256x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x256x1179648] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x256x2285568] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[256x256x4089600] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x384x2686391] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x384x2700982] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x384x2732841] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x1152x2686391] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x1152x2700982] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[384x1152x2732841] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x384x294912] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x294912] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x380668] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x693755] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x704107] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x512x705260] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x1536x380668] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x1536x693755] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x1536x704107] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x1536x705260] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x2048x288059] - AssertionError: strides must be 16-byte aligned
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[512x2048x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[768x256x73728] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[768x368x294912] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[768x992x589824] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[1024x256x73728] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[1152x512x32768] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[1152x512x49152] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[1152x512x65536] - AssertionError: Tensor-likes are not close!
FAILED third_party/tlx/tutorials/testing/test_correctness.py::test_blackwell_gemm_more_shapes[1152x640x258048] - AssertionError: Tensor-likes are not close!
```

Reviewed By: htyu

Differential Revision: D95232949

Pulled By: dshi7

fbshipit-source-id: da57b74cbe7f56e53088eb0ed34e876c7d3ebfdb