Revert D85686892 (#530)
Summary:
Pull Request resolved: https://github.com/facebookexperimental/triton/pull/530

This diff reverts D85686892
/data/users/daohang/fbtriton/third_party/tlx/tutorials/blackwell-gemm-ws.py:116:44: error: Result has an invalid layout: Could not determine the number of warps per CTA. Operation is not in a context with `ttg.num-warps`.
                    result = tlx.local_load(acc_tmem_subslice1)

Depends on D85686892

Reviewed By: dshi7

Differential Revision: D85779224

fbshipit-source-id: 464f5efe297067606e21d3b54a41c5aade777ae1