Revert D85686892
Summary:
This diff reverts D85686892
/data/users/daohang/fbtriton/third_party/tlx/tutorials/blackwell-gemm-ws.py:116:44: error: Result has an invalid layout: Could not determine the number of warps per CTA. Operation is not in a context with `ttg.num-warps`.
                    result = tlx.local_load(acc_tmem_subslice1)

Depends on D85686892

Differential Revision: D85779224