[TLX][CLC] Fix the final trailing remote bar arrive in the last consumer call (#1108)
Summary:
In multi cta context, cta0 will be the only producer. It fetches new tile id for both ctas. cta1's consumer will wait for the tile id, extract it, arrive a bar of cta0 to notify the producer to continue, and then return the tile id.

The issue is this: if the extracted tile id is -1, it means there's no more work to steal, and there won't be another producer call. When cta1 gets a -1 tile id, it should just skip the final arrive of the bar of cta0. Otherwise, cta0 could have already exited now, and cta1 would be issuing an invalid DSMEM access.

Pull Request resolved: https://github.com/facebookexperimental/triton/pull/1108

Test Plan:
added a unit test to simulate the case described here. The test now passes. Without this fix, the test would fail with this message below.

I wrote a small note on how to use compute sanitizer to catch issues like this next time. It's a bit lengthy so separating to a gist: https://gist.github.com/pchen7e2/81317cb57ed6aafcb3f98dfadd99cd58. (hint: `compute-sanitizer --tool synccheck` did it)

Original error message:
```
========================================================================================== FAILURES ===========================================================================================
_____________________________________________________________________ test_cluster_launch_control_multi_cta_delayed_exit ______________________________________________________________________

self = <[AcceleratorError("CUDA error: unspecified launch failure\nSearch for `cudaErrorLaunchFailure' in https://docs.nvidia...h `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n") raised in repr()] TensorLikePair object at 0xfffdb0246120>

    def compare(self) -> None:
        actual, expected = self.actual, self.expected

        self._compare_attributes(actual, expected)
        if any(input.device.type == "meta" for input in (actual, expected)):
            return

        actual, expected = self._equalize_attributes(actual, expected)
>       self._compare_values(actual, expected)

../miniconda3/lib/python3.13/site-packages/torch/testing/_comparison.py:747:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../miniconda3/lib/python3.13/site-packages/torch/testing/_comparison.py:905: in _compare_values
    compare_fn(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AcceleratorError("CUDA error: unspecified launch failure\nSearch for `cudaErrorLaunchFailure' in https://docs.nvidia...h `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n") raised in repr()] TensorLikePair object at 0xfffdb0246120>
actual = <[AcceleratorError("CUDA error: unspecified launch failure\nSearch for `cudaErrorLaunchFailure' in https://docs.nvidia...pile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n") raised in repr()] Tensor object at 0xfffdb01d14f0>
expected = <[AcceleratorError("CUDA error: unspecified launch failure\nSearch for `cudaErrorLaunchFailure' in https://docs.nvidia...pile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n") raised in repr()] Tensor object at 0xfffdb01d1680>

    def _compare_regular_values_close(
        self,
        actual: torch.Tensor,
        expected: torch.Tensor,
        *,
        rtol: float,
        atol: float,
        equal_nan: bool,
        identifier: Optional[Union[str, Callable[[str], str]]] = None,
    ) -> None:
        """Checks if the values of two tensors are close up to a desired tolerance."""
>       matches = torch.isclose(
            actual, expected, rtol=rtol, atol=atol, equal_nan=equal_nan
        )
E       torch.AcceleratorError: CUDA error: unspecified launch failure
E       Search for `cudaErrorLaunchFailure' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
E       CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E       For debugging consider passing CUDA_LAUNCH_BLOCKING=1
E       Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../miniconda3/lib/python3.13/site-packages/torch/testing/_comparison.py:1084: AcceleratorError

During handling of the above exception, another exception occurred:

device = 'cuda'

    pytest.mark.skipif(not is_blackwell(), reason="Need Blackwell")
    def test_cluster_launch_control_multi_cta_delayed_exit(device):
      ...

        clc_delayed[grid](
            x,
            y,
            output,
            n_elements,
            BLOCK_SIZE=BLOCK_SIZE,
            CLUSTER_SIZE=CLUSTER_SIZE,
            ctas_per_cga=(CLUSTER_SIZE, 1, 1),
        )

>       torch.testing.assert_close(output, ref_out)

python/test/unit/language/test_tlx.py:4073:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../miniconda3/lib/python3.13/site-packages/torch/testing/_comparison.py:411: in __repr__
    f"    {name}={value!s},"
                 ^^^^^^^^^
../miniconda3/lib/python3.13/site-packages/torch/_tensor.py:573: in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../miniconda3/lib/python3.13/site-packages/torch/_tensor_str.py:724: in _str
    return _str_intern(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../miniconda3/lib/python3.13/site-packages/torch/_tensor_str.py:643: in _str_intern
    tensor_str = _tensor_str(self, indent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
../miniconda3/lib/python3.13/site-packages/torch/_tensor_str.py:375: in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AcceleratorError("CUDA error: unspecified launch failure\nSearch for `cudaErrorLaunchFailure' in https://docs.nvidia...pile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n") raised in repr()] Tensor object at 0xfffdb01d14f0>

    def get_summarized_data(self):
        dim = self.dim()
        if dim == 0:
            return self
        if dim == 1:
            if self.size(0) > 2 * PRINT_OPTS.edgeitems:
>               return torch.cat(
                    (self[: PRINT_OPTS.edgeitems], self[-PRINT_OPTS.edgeitems :])
                )
E               torch.AcceleratorError: CUDA error: unspecified launch failure
E               Search for `cudaErrorLaunchFailure' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
E               CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E               For debugging consider passing CUDA_LAUNCH_BLOCKING=1
E               Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../miniconda3/lib/python3.13/site-packages/torch/_tensor_str.py:401: AcceleratorError
=================================================================================== short test summary info ===================================================================================
FAILED python/test/unit/language/test_tlx.py::test_cluster_launch_control_multi_cta_delayed_exit - torch.AcceleratorError: CUDA error: unspecified launch failure
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================================== 1 failed in 3.39s ========================================================================
```

Reviewed By: htyu

Differential Revision: D97233496

Pulled By: pchen7e2

fbshipit-source-id: 89bb51aaea9a11136aadb8c6fb9178d42dcd031d